elifesciences/data-science-dags

charts/peerscout/templates/ingress.yaml
https://github.com/elifesciences/data-hub-issues/issues/190
=> updated ingress path

charts/peerscout/templates/NOTES.txt
https://github.com/elifesciences/data-hub-issues/issues/190
=> removed .path from notes

README.md, data_science_pipeline/peerscout/api/input-json-schema.json, data_science_pipeline/peerscout/api/main.py, example-data/peerscout-api-request1.json, example-data/peerscout-api-request2.json, requirements.api.txt
https://github.com/elifesciences/data-hub-issues/issues/190
=> Improve dummy api

README.md, data_science_pipeline/peerscout/api/main.py
access token replaced by basic auth
=> Remove access token for peerscout API

tests/peerscout/api/main_test.py
https://github.com/elifesciences/data-hub-issues/issues/214
=> added test for peerscout api

Dockerfile.peerscout_api, Makefile, docker-compose.override.yml, docker-compose.yml, peerscout_api/main.py, tests_peerscout_api/main_test.py
https://github.com/elifesciences/data-hub-issues/issues/206
=> Fix test for api

README.md, peerscout_api/main.py, peerscout_api/recommend_editor.py
https://github.com/elifesciences/data-hub-issues/issues/208
=> Add institution to api email

peerscout_api/main.py
https://github.com/elifesciences/data-hub-issues/issues/232
=> added country to api html response

peerscout_api/main.py
https://github.com/elifesciences/data-hub-issues/issues/210
=> added website and pubmed urls to html text

peerscout_api/main.py
https://github.com/elifesciences/data-hub-issues/issues/211
=> added new sql query for stats

peerscout_api/main.py
https://github.com/elifesciences/data-hub-issues/issues/213
=> added current_availability column to query

peerscout_api/main.py
Reverts elifesciences/data-science-dags#481
=> Revert "added current_availability column to query"

peerscout_api/main.py
https://github.com/elifesciences/data-hub-issues/issues/213
=> add_availability_for_editors

Makefile, README.md, docker-compose.override.yml, peerscout_api/main.py, peerscout_api/person_details_and_stats.sql, tests_peerscout_api/main_test.py
https://github.com/elifesciences/data-hub-issues/issues/225
=> Extend PeersScout API unit tests

charts/peerscout/templates/deployment.yaml, charts/peerscout/values.yaml
https://github.com/elifesciences/data-hub-issues/issues/242
=> added environment variable section to the chart

charts/peerscout/templates/deployment.yaml, charts/peerscout/values.yaml
https://github.com/elifesciences/data-hub-issues/issues/242
=> added volume and volumemount section to chart

Jenkinsfile
https://github.com/elifesciences/data-hub-issues/issues/201
=> configure jenkins job timeout

charts/peerscout/Chart.yaml, charts/peerscout/templates/deployment.yaml, charts/peerscout/values.yaml
https://github.com/elifesciences/data-hub-issues/issues/242
=> fixed the indentation issue in deployment template

peerscout_api/main.py, peerscout_api/person_details_and_stats.sql
https://github.com/elifesciences/data-hub-issues/issues/233
=> decreased the reaching bq count from API

peerscout_api/person_details_and_stats.sql
https://github.com/elifesciences/data-hub-issues/issues/244
=> added Dates_Not_Available_CSV  column as availability

requirements.notebook.txt
https://github.com/elifesciences/data-hub-issues/issues/200
=> added LunarCalendar

data_science_pipeline/sql/disambiguated_editor_papers.sql
https://github.com/elifesciences/data-hub-issues/issues/249
=> removed de_dev dataset

.gitignore, Makefile, data_science_pipeline/utils/bq.py, notebooks/peerscout/peerscout-recommend-reviewing-editors.ipynb, notebooks/peerscout/peerscout-recommend-senior-editors.ipynb
https://github.com/elifesciences/data-hub-issues/issues/259
=> Add tempfile size to logs

data_science_pipeline/sql/v_data_science_editor_pubmed_ids.sql
https://github.com/elifesciences/data-hub-issues/issues/262
=> fixed source table

Makefile, README.md, docker-compose.ci.yml, docker-compose.yml, peerscout_api/example-data/peerscout-api-request3.json, peerscout_api/main.py, tests_peerscout_api/end2end_tests/end2end_test.py, tests_peerscout_api/unit_tests/main_test.py
https://github.com/elifesciences/data-hub-issues/issues/278
=> Peerscout api html styling 

charts/peerscout/templates/deployment.yaml
https://github.com/elifesciences/data-hub-issues/issues/306
=> increased initialDelaySeconds from 1 to 5

notebooks/peerscout/peerscout-recommend-reviewing-editors.ipynb
Memory issues in flux cluster.
https://github.com/elifesciences/data-hub-issues/issues/293
=> Degrased logging for reviewing editor recommendation

peerscout_api/main.py, tests_peerscout_api/unit_tests/main_test.py
https://github.com/elifesciences/data-hub-issues/issues/310
=> removed line feed from recommendation html

charts/peerscout/templates/deployment.yaml, charts/peerscout/values.yaml
https://github.com/elifesciences/data-hub-issues/issues/313
=> liveness and readiness probes have been made configuriable

peerscout_api/main.py, tests_peerscout_api/unit_tests/main_test.py
https://github.com/elifesciences/data-hub-issues/issues/318
=> added double quote and html.escape function between url

Dockerfile.airflow
elifesciences/data-hub-issues#329
=> [data-sciences] added apt-key command

requirements.api.txt, requirements.notebook.txt
https://github.com/elifesciences/data-hub-issues/issues/369
=> Materialize view issue because of botocore version

data_science_pipeline/utils/bq.py, data_science_pipeline/utils/pandas.py
https://github.com/elifesciences/data-hub-issues/issues/388
=> Improve memory usage of editor recommendation pipeline

data_science_pipeline/utils/bq.py, notebooks/peerscout/peerscout-recommend-reviewing-editors.ipynb, requirements.api.txt, requirements.notebook.txt
https://github.com/elifesciences/data-hub-issues/issues/388
=> Degreasing memory consumption in reviewing editor recommendation notebook

requirements.notebook.txt
```
hazal@Hazals-MacBook-Pro ~ % kubectl logs -n data-hub statefulset/data-hub--stg-worker check-db
Traceback (most recent call last):
File "/home/airflow/.local/bin/airflow", line 25, in <module>
from airflow.configuration import conf
File "/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py", line 43, in <module>
from flask_admin import BaseView
File "/home/airflow/.local/lib/python3.7/site-packages/flask_admin/__init__.py", line 6, in <module>
from .base import expose, expose_plugview, Admin, BaseView, AdminIndexView  # noqa: F401
File "/home/airflow/.local/lib/python3.7/site-packages/flask_admin/base.py", line 6, in <module>
from flask import Blueprint, current_app, render_template, abort, g, url_for
File "/home/airflow/.local/lib/python3.7/site-packages/flask/__init__ …
```
=> added MarkupSafe==2.0.1 explicitly

Dockerfile.airflow, Makefile, docker-compose.override.yml, docker-compose.yml, requirements.dag.txt, worker.sh
https://github.com/elifesciences/data-hub-issues/issues/321
=> Remove dask dependency 

requirements.notebook.txt
https://github.com/elifesciences/data-hub-issues/issues/422
https://github.com/googleapis/python-bigquery/issues/1188
=> staging failures not found 'db_types'

data_science_pipeline/utils/pubmed.py
https://github.com/elifesciences/data-hub-issues/issues/427
=> fix the failure on Data_Science_PeerScout_Get_Editor_Pubmed_Papers

Dockerfile.airflow, Makefile, config/webserver_config.py, docker-compose.yml, requirements.dag.txt
https://github.com/elifesciences/data-hub-issues/issues/121
=> Upgrade airflow to version 2.3.0

notebooks/peerscout/peerscout-recommend-reviewing-editors.ipynb
https://github.com/elifesciences/data-hub-issues/issues/421
=> added mode WRITE_TRUNCATE to load table

notebooks/forecasting/forecast-timeseries.ipynb
https://github.com/elifesciences/data-hub-issues/issues/428
=> added logs to forecast timeseried pipeline

Dockerfile.airflow, Dockerfile.jupyter, Dockerfile.peerscout_api, requirements.notebook.txt
https://github.com/elifesciences/data-hub-issues/issues/453
=> Upgrade Python for Numpy security issue

peerscout_api/main.py
Log is added to see API response json while loading the it to BQ.
=> added log for api json

requirements.api.txt, requirements.dev.txt, requirements.notebook.txt
https://github.com/elifesciences/data-hub-issues/issues/373
=> Upgrade boto3 to newer version

requirements.notebook.txt
https://github.com/elifesciences/data-hub-issues/issues/496
=> updgraded joblib to version 1.2.0

Dockerfile.airflow, data_science_pipeline/utils/dags.py, requirements.dag.txt
https://github.com/elifesciences/data-hub-issues/issues/496
=> Upgrade python packages related to security issues

peerscout_api/main.py, tests_peerscout_api/unit_tests/main_test.py
https://github.com/elifesciences/data-hub-issues/issues/503
=> Fix Peerscout API html order issue

.pylintrc, data_science_pipeline/peerscout/models.py, data_science_pipeline/sql/__init__.py, data_science_pipeline/utils/bq.py, data_science_pipeline/utils/bq_schema.py, data_science_pipeline/utils/europepmc.py, data_science_pipeline/utils/io.py, data_science_pipeline/utils/json.py, data_science_pipeline/utils/pubmed.py, notebooks/peerscout/peerscout-get-editor-pubmed-paper-ids.ipynb, peerscout_api/main.py, requirements.dev.txt, setup.py, tests/conftest.py, tests/utils/bq_test.py, tests/utils/pubmed_test.py, tests_peerscout_api/end2end_tests/end2end_test.py
https://github.com/elifesciences/data-hub-issues/issues/536
=> Upgraded Pylint

data_science_pipeline/sql/editor_publication_ids.sql, data_science_pipeline/sql/publications_extracted_keywords.sql
https://github.com/elifesciences/data-hub-issues/issues/568
=> Handle six digit manuscript ids

data_science_pipeline/sql/Manuscript_Version_Matching_Editor_Profile.sql, data_science_pipeline/sql/Manuscript_Version_Matching_Reviewing_Editor_Profile.sql, data_science_pipeline/sql/manuscript-version-initial-submissions-for-senior-editor-recommendation.sql, data_science_pipeline/sql/reviewing-editor-assignments.sql, data_science_pipeline/sql/senior-editor-assignments.sql
https://github.com/elifesciences/data-hub-issues/issues/617
=> Add RP site data to Peerscout Recommendation Dashboard

.dockerignore, .gitignore, Dockerfile.airflow, Makefile
=> Fix nbextension related CI build errors

requirements.api.txt, requirements.dev.txt, requirements.notebook.txt
https://github.com/elifesciences/data-hub-issues/issues/787
=> Add `Urllib3` into requirements and pinned `types-requests`

data_science_pipeline/sql/editor_publication_ids.sql, data_science_pipeline/sql/publications_extracted_keywords.sql
https://github.com/elifesciences/data-hub-issues/issues/667
=> Fix regex to handle with `format` function

Makefile
https://github.com/elifesciences/data-hub-issues/issues/846
=> Update `db upgrade` command to `db migrate` command

Dockerfile.airflow, requirements.dag.txt
Reverts elifesciences/data-science-dags#616
=> Revert "Upgrade Airflow to version 2.8.1"

Dockerfile.airflow, docker-compose.yml, requirements.dag.txt
it has been missed to upgraded 
https://github.com/elifesciences/data-hub-issues/issues/754
=> Upgrade Airflow to version 2.7.1

data_science_pipeline/utils/bq.py
With that change, this error message looks more like:
> peerscout-api_1      | google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details.; Error while reading data, error message: JSON processing encountered too many errors, giving up. Rows: 1; errors: 1; max bad: 0; error percent: 0; Error while reading data, error message: JSON parsing error in row starting at position 0: No such field: provenance.recommendation_request.assigned_deputy_editors_id.
=> Show more detailed BigQuery load error message

docker-compose.override.yml
=> Export PeerScout API port on host

data_science_pipeline/utils/pubmed.py, tests/utils/pubmed_test.py
part of https://github.com/elifesciences/data-hub-issues/issues/586
=> Raise assertion error if hostname is none for Pubmed URL

requirements.notebook.txt
```log
[2024-07-15, 10:30:50 UTC] {kernelspec.py:293} WARNING - Kernelspec name python3 cannot be found!
[2024-07-15, 10:30:50 UTC] {manager.py:89} ERROR - No such kernel named python3
Traceback (most recent call last):
File "/home/airflow/.local/lib/python3.8/site-packages/jupyter_client/manager.py", line 82, in wrapper
out = await method(self, *args, **kwargs)
File "/home/airflow/.local/lib/python3.8/site-packages/jupyter_client/manager.py", line 391, in _async_start_kernel
kernel_cmd, kw = await ensure_async(self.pre_start_kernel(**kw))
File "/home/airflow/.local/lib/python3.8/site-packages/jupyter_client/utils.py", line 38, in ensure_async
return await obj
File "/home/airflow/.local/lib/python3.8/site-packages/jupyter_client/manager.py", line 353, in _async_pre_start_kernel …
```
=> Rollback ipywidgets version to 7.6.3

data_science_pipeline/utils/pubmed.py
https://github.com/elifesciences/data-hub-issues/issues/586
=> Make get_pmids return a list

.env, Jenkinsfile, Makefile, docker-compose.yml
https://github.com/elifesciences/data-hub-issues/issues/965
=> Pushing 'elifesciences/data-science-dags' image

Jenkinsfile
part of https://github.com/elifesciences/data-hub-issues/issues/1002
=> Do not trigger combined Data Hub Airflow Image anymore

Makefile, README.md, data_science_pipeline/cli/peerscout_get_editor_pubmed_papers.py, data_science_pipeline/cli/peerscout_recommend_reviewing_editors.py, data_science_pipeline/cli/peerscout_recommend_senior_editors.py, docker-compose.override.yml, docker-compose.yml, notebooks/peerscout/peerscout-recommend-reviewing-editors.ipynb
part of https://github.com/elifesciences/data-hub-issues/issues/1005
=> Added make targets to run pipelines via Docker

Jenkinsfile
Part of https://github.com/elifesciences/data-hub-issues/issues/1005
=> Removed the code related to triggering airflow image build (which missed before)

data_science_pipeline/sql/manuscript-version-extracted-keywords.sql, data_science_pipeline/sql/manuscript-version-initial-submissions-for-senior-editor-recommendation.sql, data_science_pipeline/sql/publications_extracted_keywords.sql, notebooks/peerscout/peerscout-build-reviewing-editor-profiles.ipynb, notebooks/peerscout/peerscout-build-senior-editor-profiles.ipynb
part of https://github.com/elifesciences/data-hub-issues/issues/1046
=> Use new SpaCy API created tables
